# Generated by Django 4.2.9 on 2024-02-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("todo_name", models.CharField(max_length=100)),
                ("todo_finished", models.BooleanField(default=False)),
                ("todo_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
